<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>api request</title>
  </head>
  <body>
    <h2>api calls with async and await...</h2>
    <script>
      // method 1
      //   let url = "https://catfact.ninja/fact";
      //   async function printCatfact() {
      //     let response1 = await fetch(url);
      //     let data1 = await response1.json();
      //     console.log("response1 is =\n", response1);
      //     console.log("fact1 is =\n", data1);
      //     let response2 = await fetch(url);
      //     let data2 = await response2.json();
      //     console.log("response2 is =\n", response2);
      //     console.log("fact2 is =\n", data2);
      //     let response3 = await fetch(url);
      //     let data3 = await response3.json();
      //     console.log("response3 is =\n", response3);
      //     console.log("fact3 is =\n", data3);
      //   }
      //   printCatfact();
      //method 2
      // using error handling try & catch...
      let url = "https://catfact.ninja/fact";
      async function printCatfact() {
        try {
          let response1 = await fetch(url);
          let data1 = await response1.json();
          console.log("response1 is =\n", response1);
          console.log("fact1 is =\n", data1);
          let response2 = await fetch(url);
          let data2 = await response2.json();
          console.log("response2 is =\n", response2);
          console.log("fact2 is =\n", data2);
          let response3 = await fetch(url);
          let data3 = await response3.json();
          console.log("response3 is =\n", response3);
          console.log("fact3 is =\n", data3);
        } catch (error) {
          console.log("error...", error);
        }
      }
      printCatfact();
    </script>
  </body>
</html>
