<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Async-Await With try & catch</title>
  </head>
  <body>
    <h1>Async-Await With try & catch</h1>

    <h2>
      How to Handle Errors in Async/Await To handle an error that might occur
      from the async/await syntax, you can use the try/catch block to catch any
      rejection from your promise.
    </h2>
    <h4>
      JavaScript is Synchronous in nature which means that it has an event loop
      that allows you to queue up an action that wonâ€™t take place until the loop
      is available sometime after the code that queued the action has finished
      executing. But there are a lot of functionalities in our program that make
      our code Asynchronous and one of them is the Async/Await functionality.
    </h4>
    <h3>
      Async/Await is the extension of promises that we get as support in the
      language.<br />

      What is Async Function ? Async simply allows us to write promises-based
      code as if it was synchronous and it checks that we are not breaking the
      execution thread.
      <br />
      Async functions will always return a value. It makes sure that a promise
      is returned and if it is not returned then JavaScript automatically wraps
      it in a promise which is resolved with its value.
    </h3>
    <h2>
      <b> What is Await Function ?</b>
      Await function is used to wait for the promise. It could be used within
      the async block only. It makes the code wait until the promise returns a
      result.
    </h2>
    <script>
      // Method 2 with API's
      //   async function runProcess() {
      //     const response = await fetch(
      //       "https://jsonplaceholder.typicode.com/todos/1"
      //     );
      //     const json = await response.json();
      //     console.log(json);
      //   }

      //   runProcess();

      // Method 2 with API's with Error Handling...try & catch:
      async function runProcess() {
        try {
          const response = await fetch(
            "https://jsonplaceholder.typicode.com/todos/1"
          );
          const json = await response.json();
          console.log(json);
        } catch (error) {
          console.log(error);
        }
      }

      runProcess();

      // Method-3..with API's
      //   async function fetchData() {
      //     // Asynchronous operation
      //     const data = await fetch("https://jsonplaceholder.typicode.com/posts");

      //      Once the promise is resolved, continue execution
      //     let response = data.json();
      //     console.log(response);
      //   }
      //   fetchData();

      // Method 2 with API's with Error Handling...try & catch:
      async function fetchData() {
        try {
          const response = await fetch(
            "https://jsonplaceholder.typicode.com/posts"
          );
          const data = await response.json();
          //      Once the promise is resolved, continue execution

          console.log(data);
        } catch (error) {
          console.error("Error fetching data:", error);
        }
      }
      fetchData();
    </script>
  </body>
</html>
